import { pgTable, varchar, integer, bigint, text, index } from 'drizzle-orm/pg-core';

export const orders = pgTable(
  'orders',
  {
    id: text('id').primaryKey(),
    chainId: integer('chain_id').notNull(),
    poolId: varchar('pool_id').notNull(),
    orderId: bigint('order_id', { mode: 'bigint' }).notNull(),
    transactionId: text('transaction_id'),
    userAddress: varchar('user_address'),
    side: varchar('side'),
    timestamp: integer('timestamp'),
    price: bigint('price', { mode: 'bigint' }),
    quantity: bigint('quantity', { mode: 'bigint' }),
    filled: bigint('filled', { mode: 'bigint' }),
    type: varchar('type'),
    status: varchar('status'),
    expiry: integer('expiry'),
    autoRepay: varchar('auto_repay'),
    autoBorrow: varchar('auto_borrow'),
    timeInForce: varchar('time_in_force'),
    quoteQuantity: bigint('quote_quantity', { mode: 'bigint' }),
    executedQuoteQuantity: bigint('executed_quote_quantity', { mode: 'bigint' }),
    agentTokenId: bigint('agent_token_id', { mode: 'bigint' }),
    executor: varchar('executor'),
  },
  (table) => ({
    orderIdChainIdx: index('orders_order_id_chain_idx').on(table.orderId, table.chainId),
    poolChainStatusIdx: index('orders_pool_chain_status_idx').on(table.poolId, table.chainId, table.status),
    poolStatusSideIdx: index('orders_pool_status_side_idx').on(table.poolId, table.status, table.side),
    depthOptimizedIdx: index('orders_depth_optimized_idx').on(table.poolId, table.status, table.side, table.price),
    userTimestampIdx: index('orders_user_timestamp_idx').on(table.userAddress, table.timestamp),
    userStatusTimestampIdx: index('orders_user_status_timestamp_idx').on(table.userAddress, table.status, table.timestamp),
    poolIdx: index('orders_pool_idx').on(table.poolId),
    statusIdx: index('orders_status_idx').on(table.status),
    timestampIdx: index('orders_timestamp_idx').on(table.timestamp),
    userIdx: index('orders_user_idx').on(table.userAddress),
  })
);
